name = input("What’s your name? ")
age = input("How old are you? ")
color = input("What's your favorite color? ")
sex = input("What's your sex?")
print("Hello " + name + "! You are " + age + " years old and are a " + sex + "and your favorite color is " + color +)
